//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace my_pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookMan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookMan()
        {
            this.BookMansProfessions = new HashSet<BookMansProfession>();
        }
    
        public long PK_BookMansID { get; set; }
        public Nullable<System.DateTime> Worksince { get; set; }
        public string Description { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public Nullable<System.DateTime> Bdate { get; set; }
        public string Gender { get; set; }
        public Nullable<long> Fk_Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookMansProfession> BookMansProfessions { get; set; }
    }
}
