//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace my_pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.BookImages = new HashSet<BookImage>();
            this.BookRates = new HashSet<BookRate>();
            this.BookTags = new HashSet<BookTag>();
            this.Comments = new HashSet<Comment>();
            this.Favorites = new HashSet<Favorite>();
            this.InvoiceInfoes = new HashSet<InvoiceInfo>();
            this.SellingInfoes = new HashSet<SellingInfo>();
        }
    
        public long PK_BookID { get; set; }
        public string BookTitle { get; set; }
        public long Publicationyear { get; set; }
        public Nullable<long> PrintNumber { get; set; }
        public string Description { get; set; }
        public long NumberofPages { get; set; }
        public int edition { get; set; }
        public long FK_PublicationID { get; set; }
        public Nullable<long> FK_AgeCategoryID { get; set; }
        public Nullable<bool> isDeletes { get; set; }
    
        public virtual AgeCategory AgeCategory { get; set; }
        public virtual Publication Publication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookImage> BookImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookRate> BookRates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookTag> BookTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorite> Favorites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceInfo> InvoiceInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellingInfo> SellingInfoes { get; set; }
    }
}
