//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace my_pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookMansProfession
    {
        public long PK_BookMansProfessionID { get; set; }
        public long FK_BookMansID { get; set; }
        public long FK_ProfessionTypeID { get; set; }
        public Nullable<System.DateTime> Since { get; set; }
        public long Fk_BookID { get; set; }
    
        public virtual BookMan BookMan { get; set; }
        public virtual ProfessionType ProfessionType { get; set; }
    }
}
