//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace my_pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceInfo
    {
        public long Pk_InvoiceID { get; set; }
        public long FK_BookID { get; set; }
        public long Fk_memberIDseller { get; set; }
        public long Fk_memberIDbuyer { get; set; }
        public long Fk_StateID { get; set; }
        public long FK_SellingInfo { get; set; }
        public System.DateTime Date { get; set; }
        public string TrackingCode { get; set; }
        public long Fk_PayType { get; set; }
        public long Count { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual InvoiceInfo InvoiceInfo1 { get; set; }
        public virtual InvoiceInfo InvoiceInfo2 { get; set; }
        public virtual Member Member { get; set; }
        public virtual Member Member1 { get; set; }
        public virtual PayType PayType { get; set; }
        public virtual SellingInfo SellingInfo { get; set; }
        public virtual State State { get; set; }
    }
}
