//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace my_pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonSearchTag
    {
        public long PK_PersonSerachTag { get; set; }
        public long FK_TagID { get; set; }
        public long FK_MemberID { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
