//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace my_pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellingInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SellingInfo()
        {
            this.InvoiceInfoes = new HashSet<InvoiceInfo>();
        }
    
        public long Pk_SellingInfoID { get; set; }
        public long Fk_BookID { get; set; }
        public long Fk_memberID { get; set; }
        public decimal SellerPrice { get; set; }
        public decimal RealPrice { get; set; }
        public bool isUsed { get; set; }
        public string Description { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<bool> isExpired { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public bool Do_Exist { get; set; }
    
        public virtual Book Book { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceInfo> InvoiceInfoes { get; set; }
        public virtual Member Member { get; set; }
    }
}
